[server]
fileWatcherType = "poll"

[theme]
base = "dark"
primaryColor = "#00d1ff"              
backgroundColor = "#0b0f19"           
secondaryBackgroundColor = "#1a1f2e"  
textColor = "#e8f1ff"                 
font = "sans serif"     